Repository apify/workflows, pull requests merged in 2024-10, with the labels that each got.

#129 feat: add Python workflows
  .github/workflows/python/docs_check.yaml
  .github/workflows/python/integration_tests.yaml
  .github/workflows/python/lint_check.yaml
  .github/workflows/python/type_check.yaml
  .github/workflows/python/unit_tests.yaml
Labels: adhoc, infrastructure, t-tooling

#131 fix: move Python workflows to top level
  .github/workflows/python_docs_check.yaml
  .github/workflows/python_integration_tests.yaml
  .github/workflows/python_lint_check.yaml
  .github/workflows/python_type_check.yaml
  .github/workflows/python_unit_tests.yaml
Labels: adhoc, infrastructure, t-tooling

#132 ci: fix Python integration tests workflow
  .github/workflows/python_integration_tests.yaml
Labels: adhoc, infrastructure, t-tooling

#133 feat: git-cliff-release and prepare-pypi-distribution actions, python_bump_and_update_changelog workflow
  .github/workflows/python_bump_and_update_changelog.yaml
  git-cliff-release/README.md
  git-cliff-release/action.yaml
  git-cliff-release/cliff.toml
  git-cliff-release/fetch_pr_issues.sh
  git-cliff-release/preprocess_commit_message.py
  prepare-pypi-distribution/README.md
  prepare-pypi-distribution/action.yaml
Labels: adhoc, t-tooling

#135 refactor: Rework changelog formatting in git-cliff-release action
  .gitignore
  git-cliff-release/action.yaml
  git-cliff-release/cliff.toml
  git-cliff-release/enhance_context.py
  git-cliff-release/fetch_pr_issues.sh
  git-cliff-release/preprocess_commit_message.py
Labels: t-tooling

#137 fix: git-cliff-release release notes format
  git-cliff-release/enhance_context.py
Labels: adhoc, t-tooling

#138 ci: Ignore more kinds of beta tags in git-cliff-release
  git-cliff-release/action.yaml
Labels: adhoc, t-tooling

#139 ci: Adjust closed issue rendering in git-cliff-release
  git-cliff-release/cliff.toml
  git-cliff-release/enhance_context.py
Labels: adhoc, t-tooling

#140 fix: Fix PR link in git-cliff-release
  git-cliff-release/enhance_context.py
Labels: adhoc, t-tooling

#141 fix: Fix extra newline in git-cliff-release
  git-cliff-release/cliff.toml
Labels: adhoc, t-tooling

#142 feat: Allow prepending the generated changelog to an existing one in git-cliff-release
  git-cliff-release/README.md
  git-cliff-release/action.yaml
  git-cliff-release/cliff.toml
  git-cliff-release/enhance_context.py
Labels: adhoc, t-tooling

#144 feat: Also remove alpha tags in git-cliff-release action
  git-cliff-release/action.yaml
Labels: adhoc, t-tooling
