Repository apify/workflows, pull requests merged in 2024-11, with the labels that each got.

#146 fix: Use correct link to releases in git-cliff-release action
  git-cliff-release/enhance_context.py
Labels: adhoc, t-tooling

#147 fix: Fix changelog prepending in git-cliff-release action
  git-cliff-release/action.yaml
Labels: adhoc, t-tooling

#149 chore: update Python workflows to use Python 3.13
  .github/workflows/python_bump_and_update_changelog.yaml
  .github/workflows/python_docs_check.yaml
  .github/workflows/python_integration_tests.yaml
  .github/workflows/python_lint_check.yaml
  .github/workflows/python_type_check.yaml
  .github/workflows/python_unit_tests.yaml
  git-cliff-release/fetch_pr_issues.sh
  prepare-pypi-distribution/action.yaml
Labels: adhoc, infrastructure, t-tooling

#150 fix: add tailscale sleep workaround
  .github/workflows/deploy_helmfile.yaml
Labels: adhoc, t-platform

#151 feat: add workflow permisions for relase-please; also release, please
  .github/workflows/local_release.yaml
Labels: adhoc, t-platform

#154 feat: Add httpbin_url input to python unit tests workflow
  .github/workflows/python_unit_tests.yaml
Labels: adhoc, t-tooling

#156 fix: Tailscale sleep workaround
  .github/workflows/deploy_helmfile.yaml
Labels: adhoc, t-platform
