Repository apify/workflows, pull requests merged in 2025-02, with the labels that each got.

#170 chore: parametrize runner tag for build workflow
  .github/workflows/build_docker_image_and_push_to_ecr.yaml
Labels: adhoc, infrastructure, t-platform

#171 feat: readme update
  README.md
Labels: adhoc, infrastructure, t-platform

#169 Check pyproject requirements before running unit tests
  .github/workflows/python_unit_tests.yaml
Labels: t-tooling

#173 Poetry enforce specific Python version
  .github/workflows/python_integration_tests.yaml
  .github/workflows/python_lint_check.yaml
  .github/workflows/python_type_check.yaml
  .github/workflows/python_unit_tests.yaml
Labels: adhoc, t-tooling

#174 chore: migrate from poetry to uv
  .github/workflows/python_bump_and_update_changelog.yaml
  .github/workflows/python_docs_check.yaml
  .github/workflows/python_integration_tests.yaml
  .github/workflows/python_lint_check.yaml
  .github/workflows/python_type_check.yaml
  .github/workflows/python_unit_tests.yaml
  prepare-pypi-distribution/action.yaml
Labels: infrastructure, t-tooling

#175 chore: add grafana annotation workflow
  .github/workflows/grafana_annotation.yaml
Labels: adhoc, t-platform
